LOCAL_PATH := $(call my-dir)

# DLKM_DIR was moved for JELLY_BEAN (PLATFORM_SDK 16)
DLKM_DIR := $(TOP)/device/qcom/common/dlkm

KBUILD_OPTIONS += RTL8821CU=m
KBUILD_OPTIONS += CONFIG_ANDROID=y

KBUILD_OPTIONS += MODNAME=8821cu
KBUILD_OPTIONS += BOARD_PLATFORM=$(TARGET_BOARD_PLATFORM)

include $(CLEAR_VARS)
LOCAL_MODULE              := 8821cu.ko
LOCAL_MODULE_TAGS         := optional
LOCAL_MODULE_DEBUG_ENABLE := true
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)

include $(DLKM_DIR)/AndroidKernelModule.mk
